export const CART_INFO = 'CART_INFO'
export const CART_NUM = 'CART_NUM'
export const CART_RECOMMEND = 'CART_RECOMMEND'
export const CART_ADD = 'CART_ADD'
export const CART_UPDATE = 'CART_UPDATE'
export const CART_UPDATE_CHECK = 'CART_UPDATE_CHECK'
